### ISSUE TITLE
Nested Django dir

### ISSUE THREAD

**Issue by dbrgn** [davidhalter/depl#2]
Most of my Django projects have the following structure:

```
README.rst
requirements.txt
depl.yml  # In the future?
myproj/
    manage.py
    conf/
    front/
```

Currently depl does not seem to support that. I added a way to customize the path to the manage.py module in https://github.com/dbrgn/depl/commit/e0f9c2552e840776451ffbef0a9f626dff376445. But then deployment still fails, because the autodetected settings file is imported from the root directory.

Another approach would be to put the depl file in the `myproj` directory, but then the `requirements.txt` file wouldn't be found anymore. And platforms like Heroku require the requirements file to be in the git root.

I thought about configuring a `project_dir`, which would then point to the `myproj` directory. Additionally, you would need a `requirements_file` config variable, to support requirements files in arbitrary directories

Then you could simply copy the requirements file as well as the project directory to the remote server...

**Comment by davidhalter** [comment]
Going to implement this soon. Thought about that use case a while ago, but wasn't sure how exactly people would be using it. There's probably going to be a `path` setting that you can specify, like:

```
deploy:
  - django:
      path: myproj
```

It would then search the parent nodes (and its own directory) for a requirements file. But I have to think about the exact implementation. It feels strange that the `requirements.txt` file is in a different directory.

**Comment by dbrgn** [comment]
It does not feel strange if you think about the main directory as the "project" and the subdirectory as the "code".
